### ISSUE TITLE
Issue tracker of documentation upgrade before public announce  

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/rudr#286]
Let's use this issue to track all the important documentation upgrade issues before announce, these issues should all be high priority:

- [x] 1. ~~add uninstall guide in quickstart~~  #284 #297 
- [x] 2. ~~helm install error~~  #283 #296 
- [x] 3. ~~duplicated quickstart in README and docs/quickstart can cause confusing~~  #281 #298
- [x] 4. ~~explain more about app update in quickstart~~ #280 #212  #299 
- [x] 5. ~~fix narrative in readme and clarify the complexity of current world~~ #285
- [x] 6. ~~Quick start should include minimum Kubernetes version required.~~  #256 #276 
- [x] 7. ~~Docs: Tutorial that covers the source-to-deployment case.~~ #207 
- [x] 8. ~~A user-friendly README~~ #186
- [x] 9. Package up an example into a Helm chart #203 #300 
- [x] 10. ~~Fix broken YAML in~~ #314

The rest of documentation issues are also very important but maybe a little hard and can be less priority:  

- [x] 1. ~~Topic guide: Component Schematics~~  #208 #335
- [x] 2. ~~Topic Guide: Application Configuration~~ #209 #335 
- [x] 3. ~~Topic Guide: Traits~~ #210
- [ ] 4. Topic Guide: Scopes #211 
- [x] 5. Add Volume Mounter information in docs #318 

Documentation is user's first impression, we could make it better. 💪

**Comment by wonderflow** [comment]
I think  I could  close this issue as all high priority issues have been done.
